#!/bin/sh -e

case "$1" in
  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	  echo "Do nothing"
  ;;
  remove)
      set +e
      /usr/sbin/deluser domogik
      set -e
  ;;
  purge)
      set +e
      /bin/rm -Rf /var/lib/domogik
      /bin/rm -Rf /var/log/domogik
      /bin/rm -Rf /var/run/domogik
      /bin/rm -Rf /var/cache/domogik
      set -e
  ;;
  *)
    echo "postrm called with unknown argument '$1'" 1>&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
