"""remove trigger mode, increased state

Revision ID: 2269ae8c2bc7
Revises: 481f304ccc1a
Create Date: 2016-03-15 10:51:47.298879

"""

# revision identifiers, used by Alembic.
revision = '2269ae8c2bc7'
down_revision = '481f304ccc1a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_scenario', 'state',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Unicode(length=32),
               existing_nullable=False)
    op.drop_column('core_scenario', 'trigger_mode')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_scenario', sa.Column('trigger_mode', mysql.ENUM(u'Always', u'Hysteresis'), nullable=False))
    op.alter_column('core_scenario', 'state',
               existing_type=sa.Unicode(length=32),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    ### end Alembic commands ###
