"""Upgrade field length

Revision ID: 2e6c120aa69a
Revises: 34f2d2258b7d
Create Date: 2016-02-17 09:22:51.198922

"""

# revision identifiers, used by Alembic.
revision = '2e6c120aa69a'
down_revision = '34f2d2258b7d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_device', 'name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Unicode(length=128),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_device', 'name',
               existing_type=sa.Unicode(length=128),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    ### end Alembic commands ###
