"""Added migrate table

Revision ID: 2f6f9676add1
Revises: 3cccaa2ee819
Create Date: 2017-11-09 06:30:23.669885

"""

# revision identifiers, used by Alembic.
revision = '2f6f9676add1'
down_revision = '3cccaa2ee819'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_migrate',
        sa.Column('type', sa.Enum('DEVICE', 'SENSOR', name='migratetype'), nullable=True),
        sa.Column('oldId', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('newId', sa.Integer(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('oldId', 'newId'),
        mysql_character_set='utf8',
        mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_migrate')
    ### end Alembic commands ###
