"""extend device_type_id #323

Revision ID: 2f736b443fd2
Revises: a849c7073f8
Create Date: 2016-08-29 21:11:19.112625

"""

# revision identifiers, used by Alembic.
revision = '2f736b443fd2'
down_revision = 'a849c7073f8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_device', 'device_type_id',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.Unicode(length=255),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_device', 'device_type_id',
               existing_type=sa.Unicode(length=255),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    ### end Alembic commands ###
