"""Add trigegr_mode to scenario

Revision ID: 38b868f7501a
Revises: 404f46a359dc
Create Date: 2016-02-29 08:29:21.822656

"""

# revision identifiers, used by Alembic.
revision = '38b868f7501a'
down_revision = '404f46a359dc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_scenario', sa.Column('trigger_mode', sa.Enum('Always', 'Hysteresis'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_scenario', 'trigger_mode')
    ### end Alembic commands ###
