"""Add scenario behavior thread field

Revision ID: 3ad7bd51bb91
Revises: 4b3e72313961
Create Date: 2019-01-03 15:27:05.840956

"""

# revision identifiers, used by Alembic.
revision = '3ad7bd51bb91'
down_revision = '4b3e72313961'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_scenario', sa.Column('behavior', mysql.VARCHAR(length=20), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_scenario', 'behavior')
    ### end Alembic commands ###
