"""Finish datatbase model started in 0.4

Revision ID: 49d3ea7fccfd
Revises: 1840cdc9f1da
Create Date: 2014-07-16 15:01:12.572091

"""

# revision identifiers, used by Alembic.
revision = '49d3ea7fccfd'
down_revision = '1840cdc9f1da'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_device_stats')
    op.drop_column('core_device', 'address')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_device', sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
    op.create_table('core_device_stats',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('timestamp', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('skey', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('device_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('value_num', mysql.FLOAT(), nullable=True),
    sa.Column('value_str', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], [u'core_device.id'], name=u'core_device_stats_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
