"""Change param location value type to text

Revision ID: 4b3e72313961
Revises: 2f6f9676add1
Create Date: 2018-12-17 19:06:49.269061

"""

# revision identifiers, used by Alembic.
revision = '4b3e72313961'
down_revision = '2f6f9676add1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_location_param', 'value',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_location_param', 'value',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    ### end Alembic commands ###
