"""Upgrade float precission

Revision ID: a2a3015badf
Revises: 2e6c120aa69a
Create Date: 2016-02-23 10:50:18.636131

"""

# revision identifiers, used by Alembic.
revision = 'a2a3015badf'
down_revision = '2e6c120aa69a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_sensor', 'history_round',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=53),
               existing_nullable=True)
    op.alter_column('core_sensor', 'value_max',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=53),
               existing_nullable=True)
    op.alter_column('core_sensor', 'value_min',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=53),
               existing_nullable=True)
    op.alter_column('core_sensor_history', 'original_value_num',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=53),
               existing_nullable=True)
    op.alter_column('core_sensor_history', 'value_num',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=53),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_sensor_history', 'value_num',
               existing_type=sa.Float(precision=53),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('core_sensor_history', 'original_value_num',
               existing_type=sa.Float(precision=53),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('core_sensor', 'value_min',
               existing_type=sa.Float(precision=53),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('core_sensor', 'value_max',
               existing_type=sa.Float(precision=53),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('core_sensor', 'history_round',
               existing_type=sa.Float(precision=53),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    ### end Alembic commands ###
