"""Add state field in scenarios

Revision ID: b16c5714678
Revises: a2a3015badf
Create Date: 2016-02-26 20:00:14.624394

"""

# revision identifiers, used by Alembic.
revision = 'b16c5714678'
down_revision = 'a2a3015badf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_scenario', sa.Column('state', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_scenario', 'state')
    ### end Alembic commands ###
