"""Add state column

Revision ID: e21aed8a6c73
Revises: 34dd9f4288a2
Create Date: 2017-01-20 15:43:23.522185

"""

# revision identifiers, used by Alembic.
revision = 'e21aed8a6c73'
down_revision = '34dd9f4288a2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_device', sa.Column('state', sa.Unicode(length=30), nullable=False, server_default='active'))
    op.create_index(op.f('ix_core_device_state'), 'core_device', ['state'], unique=False)
    op.drop_constraint(u'core_person_ibfk_1', 'core_person', type_='foreignkey')
    op.create_foreign_key(None, 'core_person', 'core_sensor', ['location_sensor'], ['id'], ondelete='cascade')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'core_person', type_='foreignkey')
    op.create_foreign_key(u'core_person_ibfk_1', 'core_person', 'core_sensor', ['location_sensor'], ['id'])
    op.drop_index(op.f('ix_core_device_state'), table_name='core_device')
    op.drop_column('core_device', 'state')
    ### end Alembic commands ###
