#!/bin/bash
#This file is part of B{Domogik} project (U{http://www.domogik.org}).
#
#License
#=======
#
#B{Domogik} is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#B{Domogik} is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Domogik. If not, see U{http://www.gnu.org/licenses}.
#
#@author: Maxence Dunnewind <maxence@dunnewind.net>
#@copyright: (C) 2007-2012 Domogik project
#@license: GPL(v3)
#@organization: Domogik

# Disable a plugin

DMG_ETC=/etc/domogik

function plugin_exists {
    grep -qs "^$PLUGIN *=" $DMG_ETC/domogik.cfg
    EXISTS=$?
}

function syntax {
    echo -e "Usage: dmgenplug <plugin name>
Disable a plugin

Options:
  -h, --help            show this help message and exit
  -V, --version         display Domogik version"
    exit 1
}

function version {
    # launch manager to display Domogik's version
    dmg_manager --version
}

function disable {
    sed -i "s/^$PLUGIN *=.*$/$PLUGIN =/" $DMG_ETC/domogik.cfg
}

#check params
[ $# -ne 1 ] && syntax
[ $1 = "-h" ] && syntax && exit 0
[ $1 = "--help" ] && syntax && exit 0
[ $1 = "-V" ] && version && exit 0
[ $1 = "--version" ] && version && exit 0
[ $# -eq 1 ] && PLUGIN=$1


#check if plugin exists
plugin_exists
if [ $EXISTS -eq 1 ];then
    echo "WARNING : Plugin ($PLUGIN) does not exist. Do nothing"
    exit 1
else
    disable
fi
