#!/bin/bash
#This file is part of B{Domogik} project (U{http://www.domogik.org}).
#
#License
#=======
#
#B{Domogik} is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#B{Domogik} is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Domogik. If not, see U{http://www.gnu.org/licenses}.
#
#@author: Maxence Dunnewind <maxence@dunnewind.net>
#@copyright: (C) 2007-2009 Domogik project
#@license: GPL(v3)
#@organization: Domogik

# Enable a plugin

function get_user {
    eval $(grep USER /etc/default/domogik)
    DMG_HOME=$(getent passwd $DOMOGIK_USER|cut -d ":" -f 6)
}

function plugin_exists {
    grep -qs "^$PLUGIN *=" $DMG_HOME/.domogik.cfg
    EXISTS=$?
}

function syntax {
    echo -e "$0 [-f] <plugin>\n
Enables a plugin.\n
    -f : add the plugin if it not exists in config file"
    exit 1
}

function enable {
    if [ $EXISTS -eq 1 ];then
        sed -i "s/^\[plugins\].*$/[plugins]\n$PLUGIN = enabled/" $DMG_HOME/.domogik.cfg
    else
        sed -i "s/^$PLUGIN *=.*$/$PLUGIN = enabled/" $DMG_HOME/.domogik.cfg
    fi
}

#check params
[ $# -eq 0 ] && syntax
[ $# -gt 2 ] && syntax
[ $# -eq 1 ] && PLUGIN=$1
if [ $# -gt 1 -a "$1" != "-f" ];then  
    syntax
elif [ $# -gt 1 -a "$1" == "-f" ];then  
    FORCE=1
    PLUGIN=$2
fi

#check if plugin exists
get_user
plugin_exists
if [ $EXISTS -eq 0 ];then
    enable
elif [ $FORCE ];then
    enable
else
    echo "WARNING : The plugin does not exists and '-f' not used, do nothing."
    exit 2
fi
